# EM with Observable-Dependent Mixture Weights

Mixture weight: $p_1(i)=\sigma(\eta_0 + \eta_1\,\text{age}_0 + \eta_2\ln a_0)$. Runs a few EM iterations for speed.

In [12]:
from estimate_em_obs_v1 import run_em_obs
import os, pandas as pd

In [10]:
out = "outputs_em_obs"
res = run_em_obs("./toy_panel_with_random_x.csv", outdir=out, n_a=24, gh_order=5, em_iters=3, nm_steps=20)
res

{'beta': 0.7450306249998404,
 'sigma': 2.75,
 'theta1': array([ -7.62728521,  -1.17373184, -14.13794781,  -0.29201319]),
 'theta2': array([ -3.85186409,  -0.55403624, -17.08329903,  -1.48774889]),
 'eta': array([ 0.00000000e+00, -9.10337781e-10, -4.50343778e-11]),
 'avg_p1': 0.49999999017207436}

In [13]:
out = "outputs_em_obs"
pd.read_csv(os.path.join(out, "estimates.csv"))

     param      estimate
0     beta  7.450306e-01
1    sigma  2.750000e+00
2     g0_1 -7.627285e+00
3     g1_1 -1.173732e+00
4     d0_1 -1.413795e+01
5     d1_1 -2.920132e-01
6     g0_2 -3.851864e+00
7     g1_2 -5.540362e-01
8     d0_2 -1.708330e+01
9     d1_2 -1.487749e+00
10   eta_0  0.000000e+00
11   eta_1 -9.103378e-10
12   eta_2 -4.503438e-11
13  avg_p1  5.000000e-01

In [14]:
out = "outputs_em_obs"
pd.read_csv(os.path.join(out, "responsibilities.csv")).head()

   id  omega_type1  omega_type2  p1_prior_aligned  const  age0      ln_a0
0   0          0.5          0.5               0.5    1.0  49.0  10.024748
1   1          0.5          0.5               0.5    1.0  49.0   9.408146
2   2          0.5          0.5               0.5    1.0  35.0   9.940724
3   3          0.5          0.5               0.5    1.0  34.0  10.369707
4   4          0.5          0.5               0.5    1.0  39.0   9.636231